[package]
name = "ftl-sdk-sys"
version = "0.1.0"
authors = ["Daniel Stiner <danstiner@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
